{"n_dim": 55, "n_trials": 340, "objective": "markowitz_return_on_cube", "white": "scipy_powell", "black": "dlib_default", "traceback": ["passing", "Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/humpday/comparison/eloratings.py\", line 76, in optimizer_game\n    black_best_val, black_best_x, black_feval_count = black(objective, n_trials=n_black_trials,\n  File \"/opt/hostedtoolcache/Python/3.8.15/x64/lib/python3.8/site-packages/humpday/optimizers/dlibcube.py\", line 27, in dlib_default_cube\n    best_x, best_val = find_min_global(_objective, lb, ub, n_trials)\nRuntimeError: \n\nError detected at line 63.\nError detected in file /tmp/pip-install-d94o9wlj/dlib_ba3136adcf034269975d787741725d93/tools/python/src/global_optimization.cpp.\nError detected in function double call_func(pybind11::object, const dlib::matrix<double, 0, 1>&).\n\nFailing expression was 0 < num && num < 35.\nFunctions being optimized must take between 1 and 35 scalar arguments.\n\n"], "best_val": [2580.384992400236, null], "best_x": [[6.610696135189609e-05, 0.0004531038537848227, 0.00038261484692732903, 0.00020933140769260764, 7.362997544048794e-05, 6.610696135189609e-05, 0.0001397369358118593, 0.00040201468590334575, 0.0004531038537848227, 0.0003341728190743512, 7.362997544048794e-05, 0.00033315948892972643, 6.610696135189609e-05, 0.00041977051373087314, 6.610696135189609e-05, 6.610696135189609e-05, 0.0004930768676788784, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], null], "feval_count": [341, null], "n_trials_instructed": [340, 341], "passing": [true, false], "completed": false, "winner": "incomplete", "points": null}